/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MESSAGE_H_RPCGEN
#define _MESSAGE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct suma_1_argument {
	int a;
	int b;
};
typedef struct suma_1_argument suma_1_argument;

#define EJERCICIO3 10000
#define EJERCICIO3_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  enum clnt_stat suma_1(int , int , int *, CLIENT *);
extern  bool_t suma_1_svc(int , int , int *, struct svc_req *);
extern int ejercicio3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  enum clnt_stat suma_1();
extern  bool_t suma_1_svc();
extern int ejercicio3_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_suma_1_argument (XDR *, suma_1_argument*);

#else /* K&R C */
extern bool_t xdr_suma_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MESSAGE_H_RPCGEN */
