/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
*/
#include <stdlib.h>
#include <stdio.h>

#include "message.h"


void
ejercicio3_1(char *host, int a, int b)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	int suma_1_a = a;
	int suma_1_b = b;

#ifndef	DEBUG
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = suma_1(suma_1_a, suma_1_b, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	printf("%i\n", result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ejercicio3_1 (host, 4, 5);
exit (0);
}
