/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "message.h"
#include <stdio.h>

bool_t
suma_1_svc(int a, int b, int *result,  struct svc_req *rqstp)
{
	/*
	 * insert server code here
	*/
	printf("kk\n");

	*result = a + b;

	return 1;
}

int
ejercicio3_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
