/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include<stdlib.h>
#include<stdio.h>
#include<string.h>

#include "message.h"
#include "claves.h"

int init()
{
	// create client
	CLIENT *clnt;
	char *host = getenv("IP_TUPLAS");
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	// prepare call
	enum clnt_stat retval;
	int result;

	// execute call
	retval = d_init_1(&result, clnt);
	if (retval != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy (clnt);

	return result;
}

int set_value(int key, char *value1, int N_value, double *V_value2)
{
	// create client
	CLIENT *clnt;
	char *host = getenv("IP_TUPLAS");
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	// prepare call
	enum clnt_stat retval;
	int result;
	t_vector d_set_value_1_V_value2;
	d_set_value_1_V_value2.t_vector_len = N_value;
	d_set_value_1_V_value2.t_vector_val = (double *) malloc(d_set_value_1_V_value2.t_vector_len * sizeof(double));
	memcpy(d_set_value_1_V_value2.t_vector_val, V_value2, N_value * sizeof(double));

	// execute call
	retval = d_set_value_1(key, value1, d_set_value_1_V_value2, &result, clnt);
	if (retval != RPC_SUCCESS)
	{
		clnt_perror(clnt, "call failed");
	}
	clnt_destroy(clnt);

	return result;
}

int get_value(int key, char *value1, int *N_value2, double *V_value2){
	// create client
	CLIENT *clnt;
	char *host = getenv("IP_TUPLAS");
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	// prepare call
	enum clnt_stat retval;
	get_res result;

	// execute call
	retval = d_get_value_1(key, &result, clnt);
	if (retval != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy(clnt);

	// copy result to pointers
	strcpy(value1, result.value1);
	*N_value2 = result.V_value2.t_vector_len;
	memcpy(V_value2, result.V_value2.t_vector_val, result.V_value2.t_vector_len * sizeof(double));

	return result.status;
}

int modify_value(int key, char *value1, int N_value2, double *V_value2)
{
	// create client
	CLIENT *clnt;
	char *host = getenv("IP_TUPLAS");
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	// prepare call
	enum clnt_stat retval;
	int result;
	t_vector vv2;
	vv2.t_vector_len = N_value2;
	vv2.t_vector_val = (double *) malloc(vv2.t_vector_len * sizeof(double));
	memcpy(vv2.t_vector_val, V_value2, vv2.t_vector_len * sizeof(double));

	// execute call
	retval = d_modify_value_1(key, value1, vv2, &result, clnt);
	if (retval != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy(clnt);

	return result;
}

int delete_key(int key)
{
	// create client
	CLIENT *clnt;
	char *host = getenv("IP_TUPLAS");
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	// prepare call
	enum clnt_stat retval_5;
	int result;

	// execute call
	retval_5 = d_delete_key_1(key, &result, clnt);

	return result;
}

int exist(int key)
{
	// create client
	CLIENT *clnt;
	char *host = getenv("IP_TUPLAS");
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	// prepare call
	enum clnt_stat retval;
	int result;

	//execute call
	retval = d_exist_1(key, &result, clnt);

	return result;
}