/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MESSAGE_H_RPCGEN
#define _MESSAGE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int t_vector_len;
	double *t_vector_val;
} t_vector;

struct get_res {
	char value1[256];
	t_vector V_value2;
	int status;
};
typedef struct get_res get_res;

struct d_set_value_1_argument {
	int key;
	char *value1;
	t_vector V_value2;
};
typedef struct d_set_value_1_argument d_set_value_1_argument;

struct d_modify_value_1_argument {
	int key;
	char *value1;
	t_vector V_value2;
};
typedef struct d_modify_value_1_argument d_modify_value_1_argument;

#define EJERCICIO3 10000
#define EJERCICIO3_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define d_init 1
extern  enum clnt_stat d_init_1(int *, CLIENT *);
extern  bool_t d_init_1_svc(int *, struct svc_req *);
#define d_set_value 2
extern  enum clnt_stat d_set_value_1(int , char *, t_vector , int *, CLIENT *);
extern  bool_t d_set_value_1_svc(int , char *, t_vector , int *, struct svc_req *);
#define d_get_value 3
extern  enum clnt_stat d_get_value_1(int , get_res *, CLIENT *);
extern  bool_t d_get_value_1_svc(int , get_res *, struct svc_req *);
#define d_modify_value 4
extern  enum clnt_stat d_modify_value_1(int , char *, t_vector , int *, CLIENT *);
extern  bool_t d_modify_value_1_svc(int , char *, t_vector , int *, struct svc_req *);
#define d_delete_key 5
extern  enum clnt_stat d_delete_key_1(int , int *, CLIENT *);
extern  bool_t d_delete_key_1_svc(int , int *, struct svc_req *);
#define d_exist 6
extern  enum clnt_stat d_exist_1(int , int *, CLIENT *);
extern  bool_t d_exist_1_svc(int , int *, struct svc_req *);
extern int ejercicio3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define d_init 1
extern  enum clnt_stat d_init_1();
extern  bool_t d_init_1_svc();
#define d_set_value 2
extern  enum clnt_stat d_set_value_1();
extern  bool_t d_set_value_1_svc();
#define d_get_value 3
extern  enum clnt_stat d_get_value_1();
extern  bool_t d_get_value_1_svc();
#define d_modify_value 4
extern  enum clnt_stat d_modify_value_1();
extern  bool_t d_modify_value_1_svc();
#define d_delete_key 5
extern  enum clnt_stat d_delete_key_1();
extern  bool_t d_delete_key_1_svc();
#define d_exist 6
extern  enum clnt_stat d_exist_1();
extern  bool_t d_exist_1_svc();
extern int ejercicio3_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_t_vector (XDR *, t_vector*);
extern  bool_t xdr_get_res (XDR *, get_res*);
extern  bool_t xdr_d_set_value_1_argument (XDR *, d_set_value_1_argument*);
extern  bool_t xdr_d_modify_value_1_argument (XDR *, d_modify_value_1_argument*);

#else /* K&R C */
extern bool_t xdr_t_vector ();
extern bool_t xdr_get_res ();
extern bool_t xdr_d_set_value_1_argument ();
extern bool_t xdr_d_modify_value_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MESSAGE_H_RPCGEN */
