/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "message.h"


void
ejercicio3_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	int d_set_value_1_key;
	char *d_set_value_1_value1;
	int d_set_value_1_N_value2;
	t_vector  d_set_value_1_V_value2;
	enum clnt_stat retval_3;
	get_res result_3;
	int d_get_value_1_key;
	char *d_get_value_1_value1;
	int d_get_value_1_N_value2;
	t_vector  d_get_value_1_V_value2;
	enum clnt_stat retval_4;
	int result_4;
	int d_modify_value_1_key;
	char *d_modify_value_1_value1;
	int d_modify_value_1_N_value2;
	t_vector  d_modify_value_1_V_value2;
	enum clnt_stat retval_5;
	int result_5;
	int d_delete_key_1_key;
	enum clnt_stat retval_6;
	int result_6;
	int d_exist_1_key;

#ifndef	DEBUG
	clnt = clnt_create (host, EJERCICIO3, EJERCICIO3_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = d_init_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = d_set_value_1(d_set_value_1_key, d_set_value_1_value1, d_set_value_1_N_value2, d_set_value_1_V_value2, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = d_get_value_1(d_get_value_1_key, d_get_value_1_value1, d_get_value_1_N_value2, d_get_value_1_V_value2, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = d_modify_value_1(d_modify_value_1_key, d_modify_value_1_value1, d_modify_value_1_N_value2, d_modify_value_1_V_value2, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = d_delete_key_1(d_delete_key_1_key, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = d_exist_1(d_exist_1_key, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ejercicio3_1 (host);
exit (0);
}
