/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "message.h"

bool_t
xdr_get_res (XDR *xdrs, get_res *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->value1, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_d_set_value_1_argument (XDR *xdrs, d_set_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_d_get_value_1_argument (XDR *xdrs, d_get_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_d_modify_value_1_argument (XDR *xdrs, d_modify_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}
