/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "message.h"

bool_t
xdr_t_vector (XDR *xdrs, t_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_val, (u_int *) &objp->t_vector_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_res (XDR *xdrs, get_res *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->value1, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_d_set_value_1_argument (XDR *xdrs, d_set_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_d_modify_value_1_argument (XDR *xdrs, d_modify_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}
