/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include<stdlib.h>

#include "message.h"
#include "lib.h"

bool_t d_init_1_svc(int *result, struct svc_req *rqstp)
{
	*result = init();
	printf(" %d = init();\n", *result);

	return 1;
}

bool_t d_set_value_1_svc(int key, char *value1, t_vector V_value2, int *result,  struct svc_req *rqstp)
{
	*result = set_value(key, value1, V_value2.t_vector_len, V_value2.t_vector_val);
	printf(" %d = set(%i, %c, %i, %f);\n", *result, key, value1[0], V_value2.t_vector_len, V_value2.t_vector_val[0]) ;

	return 1;
}

bool_t d_get_value_1_svc(int key, get_res *result,  struct svc_req *rqstp)
{
	result->V_value2.t_vector_val = (double *) malloc (32 * sizeof(double));

	result->status = get_value(key, result->value1, &result->V_value2.t_vector_len, result->V_value2.t_vector_val);
	printf(" %i = get(%i, %c, %i, %f);\n", result->status, key, result->value1[0], result->V_value2.t_vector_len, result->V_value2.t_vector_val[0]) ;

	return 1;
}

bool_t d_modify_value_1_svc(int key, char *value1, t_vector V_value2, int *result,  struct svc_req *rqstp)
{
	*result = modify_value(key, value1, V_value2.t_vector_len, V_value2.t_vector_val);
	printf(" %d = modify(%i, %c, %i, %f);\n", *result, key, value1[0], V_value2.t_vector_len, V_value2.t_vector_val[0]) ;

	return 1;
}

bool_t d_delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	*result = delete_key(key);
	printf(" %d = delete(%i);\n", *result, key);

	return 1;
}

bool_t d_exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	*result = exist(key);
	printf(" %d = delete(%i);\n", *result, key);

	return 1;
}

int
ejercicio3_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
